version: '3'
services:
    gamelib_db:
        image: postgres:11.9-alpine
        environment:
            POSTGRES_PASSWORD: gamelib-db-pw
            POSTGRES_USER: gamelib-db-user
            POSTGRES_DB: gamelib
        volumes:
            - gamelib-db-data:/var/lib/postgresql/data
            - ${PWD}/postgresql/postgresql.conf:/etc/postgresql.conf
        ports:
            - "5555:5432"
        command: postgres
    gamelib_api:
        build:
            context: ../
            dockerfile: GameLib.API/Dockerfile
        image: game-lib/app:latest
        environment:
            ASPNETCORE_URLS: http://+:80

        ports:
            - "5000:80"
volumes:
    gamelib-db-data: