name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore GameLib.Test
    - name: Build
      run: dotnet build GameLib.Test --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
